### PR TITLE
Update Discovery, Stoo, Viceland

### PR DESCRIPTION
**Pull request by bobbysteel**
To match theTVDB

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked

- [ ] Give a description on what the PR is for.
- [ ] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by piejanssens** [comment]
👍

**Comment by bobbysteel** [comment]
I removed them as I believe they were incorrect originally - I can't find any reference on theTVDB with that capitalization at all. Perhaps someone cleaned up a previous error on theTVDB?

**Comment by miigotu** [comment]
Still someone might have that in their db, regardless of whether it is on tvdb or not.

**Comment by bobbysteel** [comment]
Would it make more sense to just make the time zone checker case insensitive? Feels weird to have lots of dupes over time that only vary by case...

**Comment by bobbysteel** [comment]
if the locale was broken, assuming theTVDB is correct, a full refresh would fix it right and correct the case?

**Comment by miigotu** [comment]
#216 sorts and removes dupes, but it cannot be merged for a few days to give ppl a chance to update SR.
You should PR any changes to sort_and_Remove_dupes branch until #216 is merged

**Pull request merged**
