### PR TITLE
Issue #314 - https://github.com/SickRage/sickrage-issues/issues/314

### PR DESCRIPTION
**Pull request by mckinnon81**
Updated BBC Two:Europe/London to BBC TWO:Europe/London

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked

- [x] Give a description on what the PR is for.
- [ ] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by miigotu** [comment]
Actually I think you need both.

**Comment by mckinnon81** [comment]
thanks @miigotu 

I have added BBC Two back to the file.
So there are now two BBC Two Entries.

BBC TWO:Europe/London
BBC Two:Europe/London

**Comment by miigotu** [comment]
thanks.

**Pull request merged**
