### PR TITLE
Post-DMCA update

### PR DESCRIPTION
**Pull request by sharkykh**
@miigotu

Update SR news and front page with a message that the repo is back.

The message on the front page is set to appear for the duration of about a month,
and after that time, it will stay hidden until manually removed.

**Preview:**
image

### CODE REVIEW

**Comment by sharkykh** [comment]
lol unfortunately not yet..

**Comment by miigotu** [comment]
damn I was jumping the gun.  It is Aug5 now where I am, it should be back up.  I just emailed them again to get clarification.

**Comment by sharkykh** [comment]
@miigotu I have a node.js script running to notify me via a Slack PM when the repo's back up, if you want.

**Comment by miigotu** [comment]
Nah its ok, I should get an email right away.

**Pull request merged**
