### PR TITLE
Restore old networks

### PR DESCRIPTION
**Pull request by sharkykh**
I see the issues piling on the SickRage repo,
so I restored all the old ones joined by the new ones.

There is no solution, because I realized TVDB doesn't enforce the network list.
There are many, many TV shows with custom/old network names, and I can't know which are being used.

Added `-p` to easily enable this if we'll ever need to use it.
To be clear, the script now does the following:
* Removes duplicates
* Sorts alphabetically
* Adds new networks from TVDB
then writes the new list to the file.

I've explained most of it in the README, too.

Fixes SickRage/SickRage#3520
Fixes SickRage/SickRage#3521
Fixes SickRage/SickRage#3524
Fixes SickRage/SickRage#3529
Fixes SickRage/SickRage#3530
Fixes SickRage/SickRage#3531
Fixes SickRage/SickRage#3532
Fixes SickRage/SickRage#3533
Fixes SickRage/SickRage#3534
Fixes SickRage/SickRage#3535
Fixes SickRage/SickRage#3536
Fixes SickRage/SickRage#3537

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked

- [x] Give a description on what the PR is for.
- [ ] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by miigotu** [comment]
Could maybe make it scan SickRage/issues for missing networks and add them automatically?

**Comment by sharkykh** [comment]
Sounds like a job for the SickRage bot.
I'm not sure I know how to configure it.,

**Comment by sharkykh** [comment]
Just found [this magical thread on thetvdb.com](https://forums.thetvdb.com/viewtopic.php?f=3&t=7550).
I might be able to use this DB dump to my advantage :)

**Comment by miigotu** [comment]
People add/change shows on tvdb daily. Its better to leave every possible one even if it isnt currently in their db, because someone inevitably will add a removed on again at some point.

**Comment by sharkykh** [comment]
Yeah they do, but I did with this db dump, which is pretty recent is, I queried the `tvseries` table which holds the network for each show.
And now the numbers actually add up closer to the current list. It probably won't change much, so I'll only have to update like this once.
It will add all of the used networks, even the one-offs like `www.startrekofgodsandmen.net` or whatever that was lol

**Comment by miigotu** [comment]
Yeah adding missing ones programmatically from the db dumps is great, just leave the extras in though, they dont hurt anything.

**Comment by sharkykh** [comment]
Still lots of invalid networks. Total is the same as we now have + 1 new network.

I still think those 1334 invalid networks are unused, but this is your call :)
```
New network:    puhutv    -    Turkey    -    Europe/Istanbul          

New file created [network_timezones.txt]
	Total                       : 1284
	New with time zone          : 1
	New without time zone       : 0
	Duplicates:                 : 0
	Invalid networks added      : 1334
```

**Pull request merged**
