### PR TITLE
Update network_timezones.txt

### PR DESCRIPTION
**Pull request by durrillj**
Fixed naming issues for the following 4 networks showing up in the error logs:

2016-03-26 12:22:40 Thread-15 :: [1847f03] Missing time zone for network: TV Saitama
2016-03-26 12:22:40 Thread-15 :: [1847f03] Missing time zone for network: TVK
2016-03-26 12:22:40 Thread-15 :: [1847f03] Missing time zone for network: BS-i
2016-03-26 12:22:39 Thread-15 :: [1847f03] Missing time zone for network: TV Kanagawa

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked

- [x] Give a description on what the PR is for.
- [ ] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by durrillj** [comment]
I based this pull request off of master so I closed and will resubmit based on develop

**Comment by miigotu** [comment]
Hi, you can't change existing entries, however similar they seem.
The matching is case sensitive, and the existing entries are ones people have come across in their library. So if you change an existing one you break it for them.

Just add them separate.

**Comment by miigotu** [comment]
Rejected

**Comment by durrillj** [comment]
Thank you for the feedback and sorry for my confusion.  I have issued an updated pull request with additions only.

**Pull request closed without merging**
